[server]
port = 9000
host = "127.0.0.1"

[database]
url = "sqlite:pocketbase_schema.db"
max_connections = 5

[auth]
jwt_secret = "your-secret-key"
token_expiry = 3600

[api]
version = "2.0"
base_path = "/api"

[environment]
env = "development"
ssl = false